const express = require('express');
const cors = require('cors');
const app = express();
const port = 3001;
const morgan = require('morgan');
const low = require('lowdb');
const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');
const gamesRouter = require("./routes/games");

const FileSync = require('lowdb/adapters/FileSync');
const adapter = new FileSync('db.json');
const db = low(adapter);

db.defaults({ games: [] }).write();

const options = {
	swaggerDefinition: {
		openapi: "3.0.0",
		info: {
			title: "Video Games API",
			version: "1.0.0",
			description: "Video Games API autogenerated by swagger doc",
		},
		servers: [
			{
				url: "http://localhost:3001",
			},
		],
	},
	apis: ["./routes/*.js"],
};


const specs = swaggerJsdoc(options);

app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));

app.db = db;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

app.use("/games", gamesRouter);


app.listen(port, () => {
    console.log(`API served at http://localhost:${port}`);
});
